### PR TITLE
Fix comparing of deletions

### LINKED ISSUE #994: Switching index: comparing amount of deletions broken
"x <= x + y" returns false.

### PR DESCRIPTION
**Pull request by dr0i**
- rename variables
- mark important key words in log messages

Resolves #994.

### CODE REVIEW

File: src/main/java/org/lobid/resources/run/UpdateAliases.java [hunk 1]
```diff
@@ -145,13 +145,12 @@ private static void deletedCountTest() throws IOException {
...
-				("Going to compare if " + differenceDocsCountStagingVsProduction
-						+ " is less or equals " + deletionsCount
-						+ " allowing a 0.3% tolerance (i.e. " + tolerance + ")");
+		logMessage = ("Going to compare if " + differenceOfTotalHitsBetweenOldAndNew
+				+ " is less or equals " + deletionsCount
+				+ " allowing a 0.3% tolerance (i.e. " + tolerance + ")");
 		log(logMessage);
 		Assert.assertTrue(
-				deletionsCount - differenceDocsCountStagingVsProduction < tolerance);
+				differenceOfTotalHitsBetweenOldAndNew - deletionsCount < tolerance);
```
Comment (fsteeg) [inline src/main/java/org/lobid/resources/run/UpdateAliases.java]: I'm not sure I understand, is the the fix to swap the operands? Maybe I missed something, but should we not compare the *absolute* value to cover both a slightly larger and a slightly smaller new index? Something like `Math.abs(differenceOfTotalHitsBetweenOldAndNew - deletionsCount) < tolerance`?

Comment (dr0i) [reply src/main/java/org/lobid/resources/run/UpdateAliases.java]: Hm , I think it's okay to have (many) *more* docs than expected. It's a different situation if you have *less*.

Comment (fsteeg) [reply src/main/java/org/lobid/resources/run/UpdateAliases.java]: Right, of course.
